"""
upload_revit_descriptions.py
Write feature-focused descriptions (authored in-session by Claude, applying the
humanizer rules) to the 73 REV'IT! jackets. Each description leads with what
makes the jacket distinct, then gives honest pros/cons. No material/vegan
boilerplate (the site already assumes everything is vegan).

Deterministic uploader: descriptions live in DESCRIPTIONS keyed by Notion
page_id. No API/LLM call here. Writing a real Description also immunizes these
rows against the scheduled audit, which only re-processes Description-empty rows.

Run: set -a && source ./.env.local && set +a && python3 "Scheduled audit/upload_revit_descriptions.py"
"""

import os
from notion_client import Client

n = Client(auth=os.environ["NOTION_API_KEY"])

DESCRIPTIONS = {
"36f439de-397b-8152-b21a-fb65ddba404a": "The Venator H2O is a sport-touring jacket built to carry you across seasons rather than just sunny days. It pairs a partially ventilated shell with two removable layers, a thermal liner for the cold and an over-and-under hydratex waterproof liner for the wet, so one jacket covers most conditions you ride into. The fit leans sporty and comes with jeans loops and a connection zipper to lock it to your pants. Protection is solid for the category at a Class AA rating with thin CE-level 1 SEESMART armor at the shoulders and elbows. The main trade-off is that the standard armor is CE-level 1, so hard chargers may want to add the optional level 2 back protector.",
"36f439de-397b-8174-b697-f9b4b143ad5c": "The Hyperspeed 3 H2O takes styling straight from REV'IT!'s MotoGP and WorldSBK suits and makes it usable on real roads. Waterproofing is built in through an integrated hydratex G-liner, while a large vent panel behind the main zipper keeps air moving when the pace picks up. A detachable thermal liner stretches its useful season, and the cut stays comfort-focused rather than race-tight. Protection is genuinely strong here: Class AA with CE-level 2 SEEFLEX armor, room for a level 2 back protector and level 1 chest protectors, plus Tech-Air airbag compatibility. Worth knowing that the airbag fit needs one size up, so plan sizing around how you intend to wear it.",
"36f439de-397b-8114-a99e-f196721a926d": "The Hyperspeed 2 GT Air is the hot-weather member of the Hyperspeed family, built around airflow above all else. Polyester mesh and a three-layer softshell move a lot of air through the jacket while keeping the sporty graphic look intact, and it is one of REV'IT!'s lightest jackets. SEESMART CE-level 1 armor sits at the shoulders and elbows with an insert for an optional level 2 back protector. The honest limits: this is a Class A garment with no waterproofing, so it is a summer-only piece. If you ride year-round or in changeable weather, look at one of the H2O models instead.",
"36f439de-397b-8118-9e85-d5f65a818451": "The Trucker reworks the 1960s denim jacket into something you can actually ride in, using a 15.3oz CORDURA stretch denim with COOLMAX and THERMOLITE woven in for temperature regulation and movement. The payoff is a casual jacket that looks at home off the bike and earns a Class AA rating, which is high for something this understated. SEESMART CE-level 1 armor comes standard at the elbows and shoulders, with room for a level 2 back protector. Flap pockets and a connection zipper for the Safeway belt keep it practical. The catch is no waterproofing and no thermal liner, so it suits dry-weather and warmer riding rather than commuting through rain.",
"36f439de-397b-8186-8446-f758ffe92610": "The Tracer Air 2 looks like a casual overshirt but performs like a mesh summer jacket, with a full mesh outer shell that lets air reach your upper body on hot rides. It is a strong pick if you want gear that blends into streetwear yet still carries protection. SEESMART CE-level 1 armor sits at the shoulders and elbows, and there is an insert for an optional level 2 back protector. The compromises are the ones you would expect from open mesh: a Class A rating and zero weather protection, so this is a fair-weather, warm-day garment only.",
"36f439de-397b-8163-b3c7-d972217c0699": "The Triomphe hides a technical commuter jacket inside a classic hooded parka, so nobody clocks it as motorcycle gear once you are off the bike. A detachable full-sleeve thermal liner pulls out in seconds, leaving a tear-resistant, fully waterproof shell underneath, which makes it a genuine three-season city jacket. SEESMART CE-level 1 armor covers the elbows and shoulders, with an insert for an optional level 2 back protector, and there are pockets inside and out. The main limitation is its Class A rating and level 1 standard armor, which fits its urban-commute purpose more than aggressive riding.",
"36f439de-397b-81a8-a87c-d5aee15e589e": "The Bison 2 H2O is a waterproof overshirt that keeps a relaxed, off-the-bike look while shutting out the rain through a hydratex membrane. A reinforced polyester canvas at the shoulders and elbows earns it a Class AA rating, which is high for an overshirt, and an adjustable center-back vent panel lets heat escape on warmer days. SEESMART CE-level 1 armor is standard with room for an optional back protector, and a short connection zipper ties it to your jeans. The trade-off is that it has no thermal liner, so it handles rain and mild temperatures better than genuine cold.",
"36f439de-397b-814d-b007-db6b7fd37801": "The Payload is a mid-layer rather than a standalone riding jacket, built around PrimaLoft Gold insulation to add warmth under a shell or on its own around town. It belongs to the NINETYFIVE capsule and leans hard into bold graphics, lightning-bolt prints and contrast ripstop at the shoulders and elbows. As a warming layer it is genuinely useful both on and off the bike. The important caveat is that it carries no CE rating and no built-in armor, so treat it as insulation to wear with protective gear, not as your impact protection.",
"36f439de-397b-81a5-8fa9-c4869a406279": "The Morocco is a dedicated off-road jacket, developed with rally racer Pol Tarres and built for long days standing on the pegs in the dirt. A soft-shell stretch front and back with 3L lamination gives it the mobility you need on the grip-and-slip edge, and there is backpack-rivaling storage for hydration, tools and an emergency rain layer. Style is firmly vintage rally-raid cool. The big thing to understand is that it ships with no integrated impact protection at all: it is meant to be worn over a separate protection vest, and its Class B construction reflects that. This is a purpose-built dirt jacket, not a road or all-rounder choice.",
"36f439de-397b-8148-bd42-c5db0a1e9667": "The Trazada is a ride-ready sweater that channels Pol Tarres's off-bike, old-school rally style into something you can actually ride in. Despite the casual, stretchy, super-comfortable build, it carries a Class AA safety rating and CE-level 1 SEESMART armor, which is unusual for a piece this relaxed. Pol's number 13 on the back and the PT chest icon give it clear personality. The trade-offs are practical ones: no waterproofing and no thermal liner, so it is best for casual dry-weather rides where comfort and style lead the brief.",
"36f439de-397b-8163-a496-dca311f9fbc1": "The Territory 2 is a lightweight, highly ventilated off-road and trail jacket made for riders chasing mobility over weather protection. Stretch across the yoke and upper arms improves flexibility, and laser-cut holes along the collar and yoke push airflow during hard efforts. It now uses a unisex fit with updated grading, so it works for both men and women, though REV'IT! advises women to size down. SEESMART armor protects the shoulders and elbows, with a dedicated pocket for an optional back protector. Note it is Class A with no waterproofing, so it is a warm-weather, dry-conditions trail jacket.",
"36f439de-397b-81fb-9da5-dabd490a0bee": "The Sierra 2 is a ventilated off-road jersey built for warm-weather trail riding, with large mesh panels that let the breeze flow straight to your body. Unlike most jerseys it is a certified Class B over-garment, so it adds real abrasion resistance on top of being light and breathable, and the elbows are reinforced with heavy ripstop. A goggle visor wiper tucks into the front pocket for dusty days. The key thing to know is that it carries no built-in armor and is designed to go over the body-hugging Proteus protector jacket, so you need that underneath. Women should size down per REV'IT!'s guidance.",
"36f439de-397b-81e3-ae5d-d4646a9251f8": "The Worker 2 takes the look of a heritage workwear overshirt and builds it from 14oz CORDURA stretch twill, so it stays comfortable and flexible while resisting abrasion. The result earns a Class AA rating, which is high for something this casual, and SEESMART CE-level 1 armor sits at the shoulders and elbows with an insert for an optional back protector. Four bold pockets and a reflective back-yoke label keep it practical and a little more visible. As with most overshirts, there is no waterproofing or thermal layer, so this is a dry-weather, fair-temperature pick.",
"36f439de-397b-816c-b06d-cd8558e0180a": "The Arbor H2O is a short, waist-length urban commuter jacket that puts city style first without giving up wet-weather ability. A 3L hydratex membrane keeps you dry, three waterproof pockets and a sleeve card holder handle daily essentials, and fleece-lined collars add a touch of comfort on the commute. Protection is a strong point: a Class AA rating with SEESMART and SEEFLEX armor, plus an insert for a level 2 back protector. A detachable thermal liner makes it a year-round city jacket. The shorter cut is a style choice that suits commuting more than long-haul touring.",
"36f439de-397b-816d-b230-c706bbe55696": "The Stratum GTX uses a clever two-shell system rather than one jacket trying to do everything. The base is a Class AA air-mesh layer with built-in CE-level 2 SEEFLEX elbow armor and a level 2 back protector for hot, dry riding, and a 3L GORE-TEX waterproof shell zips over the top when the weather turns. Combined, the two layers give the highest protection in REV'IT!'s adventure range, with a detachable kidney belt and hydration pocket adding touring practicality. The flip side is complexity and bulk: you are managing two shells and packing the one you are not wearing, which is the price of its all-conditions range.",
"36f439de-397b-8137-ad0e-e7b5c5fed4e3": "The Poseidon 3 GTX is a seasoned adventure-touring jacket that blends 2L and 3L GORE-TEX for zero water ingress while staying breathable. Its standout feature is the patented VCS Aquadefence system with magnetic FidLock fasteners, so you can open or close vents one-handed with gloves on. A detachable thermal liner extends its range into the cold, and CE armor wraps the elbows, shoulders and chest at a Class AA rating. It is Tech-Air airbag ready, which calls for sizing up one. As a do-everything touring jacket it carries the weight and price that come with that breadth.",
"36f439de-397b-8185-be7b-efe3a121d994": "The Triomphe 2 H2O is a field-jacket-styled urban commuter that looks like everyday outerwear but hides a technical, fully waterproof build. Pull the quick-release thermal liner and you are left with a tear-resistant polyamide PWR|Shell outer that keeps the rain out across three seasons. SEESMART CE-level 1 armor covers the elbows and shoulders, with a pouch for an optional level 2 back protector, and reflective detailing adds night visibility. Its Class A rating and level 1 standard armor match its commuter purpose rather than spirited riding.",
"36f439de-397b-8145-8d0f-cd2e86bd4b0f": "The Voltiac 3 H2O is REV'IT!'s value all-weather touring jacket, and it punches above its price. A hydratex Sphere mesh G-liner keeps you dry while staying breathable, a thermal liner handles the cold, and two sealed ventilation zippers open the full length of the chest for hot days. Despite the affordable positioning, the protection matches the pricier jackets: SEESMART CE-level 1 at the shoulders and elbows with an insert for a level 2 back protector, and it is airbag ready. It also uses recycled polyester in the liners. The main compromise is its Class A rating, which is consistent with its everyday touring brief.",
"36f439de-397b-81d6-8198-cebf4a5cef9d": "The Potential GTX is a sport-leaning waterproof jacket with an athletic, slim-but-not-tight silhouette that leaves room to move. Its waterproofing comes from a GORE-TEX Z-liner that floats between the outer shell and lining, which let REV'IT! use a cleaner, more distinctive outer fabric and hide the seams. A foldable fixed hood and generous laminated reflection round it out, and a detachable thermal liner widens its season. Protection is a Class AA rating with SEESMART CE-level 1 armor and an insert for a level 2 back protector. The fixed hood is a styling commitment, so it is worth knowing it stays put rather than detaching.",
"36f439de-397b-81d5-aa11-f230e73db372": "The Flare 3 H2O is urban-sport streetwear that rides, hiding coated ventilation zippers and tailored adjustment tabs inside a modern camo design. A hydratex G-liner keeps the rain out, a detachable thermal liner keeps the heat in, and a detachable hood can go up, snap down or zip away entirely. Protection sits at a Class AA rating with SEESMART armor at the elbows and shoulders and a built-in option for a level 2 back protector. It is a strong all-conditions city jacket; the standard armor is level 1, so add the back protector if you want more.",
"36f439de-397b-813a-925f-d5aae6474181": "The Paramount GTX is a one-piece adventure-touring suit built around tried-and-tested 3L GORE-TEX Pro for full waterproofing across seasons. A single large entry zipper runs from the lower leg to the neck for easy entry, and numerous straps let you dial in the fit. VCS ventilation and patented Aquadefence panels cool the body in heat, while CE-level 2 SEEFLEX armor sits at the shoulders, elbows and knees, backed by a level 2 back protector and level 1 hip protectors. The honest consideration is that this is a full suit, a bigger commitment in cost, bulk and storage than a separate jacket, best suited to dedicated touring.",
"36f439de-397b-8116-b730-ea452e3bec60": "The Haste H2O is the waterproof entry in the NINETYFIVE capsule, leaning into loud retro graphics, lightning bolts and race-inspired prints against a color-blocked canvas. The hydratex Mesh G-liner lets you ride through rain without a second thought, a detachable thermal liner handles cooler days, and a snap-button hood detaches when you do not want it. Protection is a Class AA rating with SEESMART armor and an insert for a level 2 back protector, and it uses recycled polyester. The bold styling is the whole point here, so it suits riders who want their gear to stand out.",
"36f439de-397b-81e3-84ad-fb2219aa42ea": "The Torque 2 H2O is a ventilated urban-sport jacket with a forged carbon print and an aggressive, angular cut that gives it real street presence. A detachable hydratex Mesh G-liner keeps the rain out when needed, and a wind catcher behind the front zipper cuts cold air reaching the body. Adjustment points at the waist and arms tailor the casual-sportive fit. Protection is SEESMART CE-level 1 at the shoulders and elbows with room for a level 2 back protector. It is a Class A garment, so it prioritizes airflow and style over the highest abrasion rating.",
"36f439de-397b-8192-b181-eedea6ec6969": "The Toronto H2O is built to disappear into city life, looking like a normal jacket you could wear over business clothes without anyone spotting the protection. A PWR|Shell 500D outer with a hydratex Mesh G-liner keeps it waterproof, and SEESMART CE-level 1 armor covers the elbows and shoulders with an insert for a level 2 back protector. The full-sleeve thermal liner is detachable and even wearable separately and reversible. A detachable hood and waist and cuff adjustment add versatility. Its Class A rating fits its discreet-commuter brief rather than performance riding.",
"36f439de-397b-81d2-a8b0-ffe5e7d4ea09": "The Continent is an adaptable adventure jacket from the DIRT Series with a clever party trick: unzip the sleeves and it converts from a full-stretch softshell jacket into an off-road riding vest in moments. You can also remove the standard armor and wear it over the Proteus protector jacket when conditions get rough. As supplied it has a Class AA rating with SEESMART armor at the elbows and shoulders and an insert for a back protector. The trade-off is no waterproofing, so this is a mid-temperature, dry-conditions adventure piece rather than an all-weather one.",
"36f439de-397b-81b0-a39d-ff0d89c772d6": "The Shade H2O is a back-to-basics, entry-level waterproof jacket aimed at riders who want simple, dependable city gear without fuss. The relaxed cut pairs easily with most pants, and a hydratex Mesh G-liner keeps the rain out around town. SEESMART CE-level 1 armor sits at the shoulders and elbows with an option to add a level 2 back protector, and it comes in several colorways including camo. As an entry-level Class A jacket it keeps things straightforward: no thermal liner and a lighter abrasion rating, which is the trade for its accessible, uncomplicated approach.",
"36f439de-397b-81db-9a0f-da54307b674f": "The Denver H2O updates a heritage four-pocket design with thoughtful detailing, like a right stash pocket gusseted on a 20-degree slant for easier access while riding and waterproof pocket inners and zips throughout. PWR|Shell and CORDURA Ripstop boost abrasion resistance at the shoulders and arms, and the styling stays classic and understated. SEESMART CE-level 1 armor is standard with an insert for an optional level 2 back protector. It is a Class A all-season jacket, so it favors everyday wearability over the highest protection rating.",
"36f439de-397b-816a-a898-fb6bc34c38ea": "The Esmont is an overshirt with an oversized pocket borrowed from 1950s USMC shirts, but its real story is the 14.2oz CORDURA stretch twill that gives it a natural, almost wool-like feel while resisting abrasion. A connection zipper lets you attach it to your pants with the Safeway belt in seconds, and a secure internal pocket sits within easy reach. It earns a Class AA rating with standard SEESMART CE-level 1 armor and an insert for a back protector. Like other overshirts it has no waterproofing or thermal layer, so it is a dry-weather, mild-temperature option.",
"36f439de-397b-81df-8ffa-f3e5929ae641": "The Parabolica 2 is a motorcycle hoodie for riders who want protection without looking like they are wearing it. Built from PWR|Fleece, it stays light and flexible, with a slim coil zipper for easy movement, reflective hood detailing and thumb loops. SEESMART CE-level 1 armor sits at the shoulders and elbows, and foldable protector pockets replace bulky hook-and-loop closures to cut interference. It carries a Class AA rating, which is high for a hoodie. The trade-off is no waterproofing, so it is a casual, dry-weather layer rather than an all-weather jacket.",
"36f439de-397b-81fb-876a-ef198aa6ace0": "The Surface is an off-road jacket from the DIRT Series engineered around maximum stretch, using an open-knit PWR|Stretch construction so it moves freely while CORDURA ripstop reinforces the structure. SEESMART armor at the elbows and shoulders and the option of a back protector give it a Class AA safety rating, and parts of the inner lining use recycled polyester. It is a comfortable, mobility-first adventure piece. The main limitation is no waterproofing, so plan it for warm, dry off-road days or layer it accordingly.",
"36f439de-397b-818d-8b28-ca0a6ba0f73b": "The Seeker is a well-ventilated off-road jersey for riders who want to stand out on warm-weather trails. It uses stretchy, lightweight Lycra with ventilation holes across the arms and body for serious airflow and freedom of movement. The thing to be clear about is that it has no built-in protection at all and is designed to be worn over the Proteus protector vest, which supplies the armor. Treat it as a breathable outer layer for hot off-road riding, paired with a protector underneath, rather than standalone gear.",
"36f439de-397b-814e-af03-c8ec6a2dbf05": "The Echelon GTX is a no-frills adventure-travel jacket whose understated looks hide a well-equipped build. A laminated 2L GORE-TEX construction delivers breathable waterproofing, and CE-level 2 SEEFLEX protection at the shoulders and elbows comes standard along with a back protector, an unusually complete setup out of the box. On-demand ventilation, plentiful pockets and a neoprene collar add comfort, while adjustment at the cuffs, collar, hem and waist dials in the fit. It is a Class AA jacket that favors quiet competence over flashy styling, which is exactly its appeal.",
"36f439de-397b-81ae-84bf-c09e23f655d7": "The Territory is a single-layer mesh off-road jacket from the DIRT Series, built for riders who keep exploring trails when temperatures climb. The PWR|Mesh outer keeps air flowing constantly to the body, and CORDURA ripstop at the shoulders and arms adds durability and abrasion resistance. SEESMART CE-level 1 armor is included, and you can remove it to wear the jacket over the Proteus protector for more coverage. The active fit avoids feeling bulky. It is a Class A, warm-weather jacket with no waterproofing, so it is firmly a hot-conditions trail piece.",
"36f439de-397b-81b3-9e66-c9b70c3a4388": "The Trench 2 GTX brings adventure-grade technology to the city commuter, built from 2L nylon 600D GORE-TEX for serious rain protection. VCS Aquadefence panels at the chest open for airflow on warmer days, and large waterproof magnetic side pockets, a sleeve pocket and a Napoleon pocket keep essentials dry and reachable. A separately wearable detachable thermal liner widens its season and doubles as an off-bike layer. Protection is a Class AA rating with CE-level 2 SEEFLEX armor and an insert for a level 2 back protector. The monochromatic styling keeps it versatile from urban to natural settings.",
"36f439de-397b-8123-88d2-d8282992a4d8": "The Montana H2O is a shorter urban-commuter parka for riders who want city style with everyday weather protection. A 2L PWR|Shell with a hydratex Mesh G-liner keeps the rain out, and there are plenty of waterproof pockets for daily essentials. SEESMART CE-level 1 armor covers the elbows and shoulders with an insert for a level 2 back protector, and a detachable thermal liner makes it a genuine three-to-four-season commuter. Jeans loops and a short connection zipper tie it to your pants, and a detachable hood adds versatility. Its Class A rating suits its commuter focus rather than fast riding.",
"36f439de-397b-81aa-83f3-e9b90d096afc": "The Rough is a motocross jersey developed from the off-season gear REV'IT! supplies its MotoGP riders for staying sharp on the dirt. It uses moisture-wicking, lightweight materials and a relaxed cut sized to fit an armored shirt underneath. The key point is that it carries no built-in protection of its own and is meant to be worn over a separate armored shirt or vest. As a breathable, race-styled outer layer for the track or trails it does its job, provided you supply the armor beneath it.",
"36f439de-397b-81b9-ba17-ea01d4ae7383": "The Trailblazer is an MX-inspired off-road jersey from the DIRT Series that is more protective than the racing jerseys it borrows its look from. Strong PWR|Mesh forms the body for ventilation and abrasion resistance, with PWR|Stretch ripstop on the arms and shoulders for durability, earning a Class B over-garment rating. Thumb loops keep the sleeves from riding up, and a chest pocket includes a goggle wiper. Because of the active fit it is designed to go over the body-hugging Proteus protector jacket, so it needs that armor underneath rather than standing alone.",
"36f439de-397b-8199-a413-ea6f4545c329": "The Crux is a casual sportswear-styled sweater you can ride in without changing clothes at either end of the trip. A polyester stretch outer and inner mesh lining keep movement free, while SEESMART elbow and shoulder protectors and a Class AA rating add real safety to the relaxed look. Knitted collar and cuffs, thumb loops and a short connection zipper round it out, and it is prepared for an optional back protector. The trade-offs are no waterproofing and no thermal liner, so it suits dry, mild rides where comfort leads.",
"36f439de-397b-812b-826b-e15b08f22535": "The Offtrack 2 H2O is an all-season adventure-touring jacket built around a versatile three-mode layering system. Ventilation panels and forearm and back zippers cool you in the heat, a detachable thermal liner handles the cold, and a hydratex waterproof liner keeps you dry, with both liners wearable as standalone jackets. The waterproof liner can even go over the outer shell as the outermost layer for extreme wet weather. CE-level 2 SEEFLEX protection sits at the shoulders and elbows, with options for back and chest protectors, at a Class AA rating. The trade-off is the bulk and fiddle of managing multiple layers, which is the cost of its range.",
"36f439de-397b-81dd-8181-eb4591ab7433": "The Sierra is an MX-inspired off-road jersey from the DIRT Series, light and ventilated yet more protective than the racing jerseys it draws from. A PWR|Mesh body provides airflow and abrasion resistance, with PWR|Stretch ripstop on the arms and shoulders for durability, giving it a Class B rating. Thumb loops keep the sleeves down and a chest pocket carries a goggle wiper. Thanks to its active fit it is built to be worn over the Proteus protector jacket, so the armor comes from that layer rather than the jersey itself.",
"36f439de-397b-81c1-a12a-d0face1f6a45": "The Airwave 4 is an adventure-sport jacket designed around one priority: moving as much air as possible. A mix of softshell, ripstop, PWR|Shell Mesh and ballistic mesh with large, visible ventilation panels keeps you cool and sharp on hot rides. It is a long-running favorite in the ventilated category, earning a Class AA rating with SEESMART armor at the elbows and shoulders plus options for chest and back protectors. Laminated reflection adds low-light visibility. As a heavily ventilated jacket it offers no waterproofing, so it is built for warm, dry adventure riding.",
"36f439de-397b-817d-8444-fac84a639cb1": "The Tornado 4 H2O is a multi-season adventure-touring staple that covers the three things tour riders ask for: ventilation, waterproofing and protection. Drop the detachable thermal and waterproof liners and the 3D air-mesh chest, arms and back flow air directly to the body; reattach them and choose whether the 3L hydratex waterproof liner rides inside or outside the shell. CE-level 2 SEEFLEX protection and a Class AA rating cover the safety side, with options for back and chest protectors. Reflective panels and a sturdy hanger loop add practicality. As with all three-layer systems, the trade is the bulk of carrying the layers you are not wearing.",
"36f439de-397b-8131-8463-c089d53fa023": "The Quantum 3 Air is a hot-weather, fully ventilated mesh jacket with race-derived styling toned down for the street. Ballistic mesh directs air to the body when temperatures climb, and the slim fit hugs the body with adjustment at the upper arm, cuffs and waist to fine-tune it. SEESMART CE-level 1 armor sits at the shoulders and elbows with an insert for a level 2 back protector, at a Class AA rating, and it uses a high share of recycled polyester. The limits are clear: no waterproofing and a summer focus, so this is a warm-weather jacket to pair with denim and sneakers.",
"36f439de-397b-812b-beca-f875aa60e2c1": "The Tracer Air 3 is the most ventilated overshirt REV'IT! makes, built from the most ballistic mesh of any jacket in the collection. It blends military-shirt styling and large chest stash pockets with serious airflow, and a front zipper and collar replace the older button-up look for an upscale casual finish. SEESMART protection at the shoulders and elbows and an optional back protector keep it ride-ready at a Class AA rating, and it uses recycled polyester. Being open mesh, it offers no weather protection, so it is purely a hot-day, dry-conditions garment.",
"36f439de-397b-8106-8153-f7b39d1ee61e": "The Oakwood is an athleisure-style riding hoodie built from soft brushed heavy-knit fleece with a slightly oversized fit, about as close to a true lifestyle hoodie as riding gear gets. Knit cuffs and hem block wind drafts, a sturdy back snap keeps the hood from catching air, and reflective accents hint at its purpose. CE-level 1 SEESMART armor sits almost invisibly at the elbows and shoulders, with a designated pocket for an optional level 2 back protector, plus a connection zipper and jeans loops. It is a Class A garment with no waterproofing, so treat it as a casual, dry-weather riding layer.",
"36f439de-397b-811a-8c07-f6a6f6f5b7b8": "The Entropy H2O brings oversized, hooded outdoor-scene styling to a waterproof riding jacket, with a longer, looser silhouette and large angular pockets front and back. A hydratex G-liner keeps the rain out while a detachable thermal liner handles cooler rides. Protection is a Class AA rating with CE-level 1 SEESMART armor as standard and an option for a level 2 back protector. A standout touch is the back protector cinch system, which lets you position the protector pocket precisely despite the relaxed fit, addressing a common problem with loose jackets. The casual cut prioritizes style, so spirited riders may want the level 2 upgrade.",
"36f439de-397b-81f6-a9a7-d292b76a9289": "The Boson takes streetwear-favorite outdoor styling onto the bike, built from stretchy hydratex WindBarrier softshell in a loose-fitting cut. CE-level 1 SEESMART armor at the shoulders and elbows and a Class AA rating make it genuinely ride-ready, while a snap-secured hood and oversized angular pockets add function and character. Jeans loops and a short connection zipper attach it to your pants, and a level 2 back protector slips in easily. The key thing to know is that the WindBarrier fabric is windproof rather than fully waterproof, so it shrugs off wind and light moisture but is not a rain jacket.",
"36f439de-397b-817b-b07a-ecbe32be9f21": "The Torque 3 H2O is a versatile urban-sport jacket that adapts to changing city weather. A fully ventilated construction keeps you cool, and an integrated hydratex G-liner handles rain; detach the waterproof liner and it becomes a breezy sporty jacket in moments. It is built for all-day wear without giving up protection, with CE-level 1 SEESMART armor at the shoulders and elbows and the option of a level 2 back protector, at a Class AA rating. The standard armor is level 1, so add the back protector if you want more coverage.",
"36f439de-397b-8180-81c4-fb837ecdc7e6": "The GT-R 4 Air is a sport-touring jacket made for long, warm days, combining clean sporty looks with plenty of breathable mesh. Durable ballistic mesh and 3D air mesh keep air moving while flexible softshell reinforces the hard-wearing zones, so it stays comfortable mile after mile in the heat. REV'IT!'s thinnest CE-level 1 SEESMART armor integrates almost invisibly at the shoulders and elbows, with an easy upgrade to a level 2 back protector, at a Class AA rating. Ample pockets, fit adjustment, jeans loops and a connection zipper add practicality. With no waterproofing, it is a warm, dry-weather touring choice.",
"36f439de-397b-819f-820a-cbde3f141b1c": "The Neptune 3 GTX is an adventure-touring jacket built to handle the elements across seasons. A 2L GORE-TEX construction keeps the rain out, and a detachable thermal liner with a high collar adds warmth and coverage in the cold; remove it and the patented VCS Aquadefence system with magnetic FidLock fasteners opens up airflow, even with gloves on. Protection is a Class AA rating with CE-level 2 SEEFLEX armor and an insert for a level 2 back protector. Two large waterproof magnetic flap pockets, a back slit pocket and a sleeve card holder handle storage. Hypalon detailing and a heavy-duty hang strap lift the finish.",
"36f439de-397b-8106-891e-d15078ea2468": "The Danforth H2O is a fashion-forward urban jacket with a slightly longer cut and a 100% waterproof hydratex G-liner membrane. Large pockets in contrasting crinkled ripstop hide ventilating panels behind the chest pockets, blurring the line between style detail and function, and a bicep pocket and waterproof inner pocket add storage. An adjustable, snap-secured hood keeps it practical on and off the bike. Protection is a Class AA rating with thin CE-level 1 SEESMART armor at the shoulders and elbows, upgradeable to a level 2 back protector. It leans toward style and everyday wear, with the level 1 standard armor reflecting that.",
"36f439de-397b-8108-9ded-c3755a1d9fd9": "The Dominator 3 GTX sits at the top of REV'IT!'s adventure range, built around tried-and-tested 3L GORE-TEX Pro for full waterproofing. A detachable storm collar stows in the back pocket, detachable stretch cuffs block cold air, and redesigned VCS zippers plus Aquadefence chest panels manage airflow in heat. Protection is about as complete as it gets: award-winning CE-level 2 SEEFLEX armor at the shoulders and elbows, a level 2 back protector, prepared for divided chest protectors, and a detachable kidney belt, all at a Class AA rating with reinforced Armacor on the shoulders. The honest note is that this flagship level of feature and protection comes at a premium price and weight.",
"36f439de-397b-81d4-bcfd-eb779920e4e7": "The Cayenne 2 is a top-spec, hot-weather adventure jacket built for riders pushing hard on and off road. Its strongest mesh fabrics sit at the front, back and underarms for maximum airflow, and the protection is among the most complete in the lineup: CE-level 2 SEEFLEX shoulder and elbow armor plus a SEESOFT AIR back protector as standard, prepared for chest protectors, with connection loops for a Segur neck brace. A hydration pocket and a detachable kidney belt with a hidden stash round out a rugged, race-ready package. With its ventilated build it offers no waterproofing, so pair it with a rain layer when the weather turns.",
"36f439de-397b-81ca-a2b4-d33f8e806a87": "The Altair H2O draws on outdoor sportswear, snowboard gear especially, to create a loose-fit moto tech-fashion jacket that stands apart from typical riding kit. An asymmetrical two-way zipper with snap buttons removes bulk from the center front for comfort and gives it a smock-like look. Smart waterproofing comes from a hydratex G-liner, YKK AquaGuard zippers and rain gutters, while airflow-activated sleeve vents, a chest vent and a back exhaust keep it breathable. Protection is a Class AA rating with SEESMART CE-level 1 armor and an insert for a level 2 back protector. The relaxed, distinctive fit is the draw for riders who want something different.",
"36f439de-397b-81bb-9d02-c75adde8e97f": "The Shade 2 H2O is an all-softshell urban commuter that delivers a clean, understated look well above its price point. A mesh G-liner gives it lightweight comfort with lasting waterproofing, and a removable padded thermal liner with a padded collar adds warmth for cold-weather riding. Tonal colorways with subtly off-tone zippers keep the styling quiet and versatile. Protection is a Class AA rating with SEESMART CE-level 1 armor at the shoulders and elbows and an insert for a level 2 back protector. It is a value-focused commuter, so the standard armor is level 1.",
"36f439de-397b-81fe-a24a-c9d1ccbe0c21": "The Hyperspeed 3 GT Air is the ventilated, long-distance member of the Hyperspeed family, built mainly from breathable yet durable mesh for warm-weather sport touring. A distinct sport-inspired chest panel uses proprietary PWR|Weave material that is both hard-wearing and highly breathable. Fit adjustment at the hem, wrists and biceps locks it in, and thin CE-level 1 SEESMART armor sits at the shoulders and elbows as standard, with pockets ready for level 2 back and level 1 chest protectors, at a Class AA rating. The trade-off is no waterproofing and a summer focus, so it shines on hot rides rather than wet ones.",
"36f439de-397b-8142-9246-ce3153b80b73": "The Atwater is a windblocker-style fashion jacket built mainly from hydratex WindBarrier softshell with contrasting crinkled ripstop on key details, so it feels as good as it looks. It carries more pocket space than comparable casual jackets, including large front stow pockets, a bicep pocket, a big inner pocket and a waterproof facing pocket, plus a ventilated windcatcher behind the main zipper. Rib-knit cuffs add a flexible, comfortable fit. Protection is a Class AA rating with nearly unnoticeable CE-level 1 SEESMART armor, upgradeable to a level 2 back protector. Note the WindBarrier fabric blocks wind rather than full rain, so it is not a dedicated waterproof jacket.",
"36f439de-397b-8129-a67e-d9d1b07a4100": "The Yaletown is a utility-minded overshirt that rethinks the ride-ready overshirt with a relaxed fit and six pockets, including asymmetric chest welts, snap-buttoned waist pockets, a bicep pocket and an inner pocket. Built from unconventional nylon crinkle fabric, it pairs casual style with genuine practicality and a Class AA rating. Underarm ventilation and a shoulder-blade exhaust vent add airflow, and an extended zipper puller and snap-secured collar keep it tidy in the wind. CE-level 1 SEESMART armor sits barely noticeably at the shoulders and elbows, with an option for a back protector. Like other overshirts, it has no waterproofing, so it is a dry-weather pick.",
"36f439de-397b-8159-a073-e9efb2947cbf": "The Saros WB is a tech-fashion hooded jacket designed to read as streetwear rather than protective gear, helped by its 3L softshell and a choice of three bold graphic prints. It is still road-ready, with inner SEESMART elbow and shoulder armor and a Class AA rating. The WB stands for wind barrier: the jacket is windproof, not waterproof, though the inner membrane helps resist water pickup. The three print options, a camo green, a tonal grey and one naming famous racetrack towns, let you pick your look. The honest limit is the lack of true waterproofing, so it handles wind and light moisture better than steady rain.",
"36f439de-397b-8130-bc71-ccba8b42a7ed": "The Vision H2O is a Pol Tarres adventure off-road jacket that blends his vintage rally style with a fit-for-purpose waterproof design. A 3L hydratex waterproof construction keeps you dry, and well-placed ventilation zippers across the biceps, lower forearms and shoulder blades manage airflow, while a hood adds casual adventure cool for off-bike downtime. CE-level 1 SEESMART armor at the elbows and shoulders is thin but effective, and you can remove it to wear the jacket over a protection vest for serious off-road riding. It is a Class A garment, which suits its off-road, layer-over-vest intent.",
"36f439de-397b-8106-aea0-f10b3746ea01": "The Defender 3 GTX is an adventure-travel jacket built for chasing distant horizons in any weather. A detachable waterproof liner with a 3L GORE-TEX membrane handles rain, a removable thermal liner covers the cold, and an unusually generous set of vents, VCS panels, arm and back zippers and a mesh panel behind the main zipper, moves serious air in the heat. Protection comes from CE-level 2 SEEFLEX armor at the shoulders and elbows, backed by a highly abrasion-resistant shell and a protective multi-layer print on the elbows, at a Class AA rating. As a full-feature travel jacket, it carries the weight and complexity that range demands.",
"36f439de-397b-81fd-ac6e-c8411ad0284a": "The Thirteen is an all-out Pol Tarres statement jersey, named for his race number and decked in his red-and-black style for trails and rally adventures. Built from durable, stretchy, lightweight Lycra, it gives you the flexibility and breathability needed for hot off-road riding. The clear caveat is that it is an overshirt only with no impact protection, designed to be worn over a protection vest. As a comfortable, breathable outer layer with strong personality it delivers, provided you supply the armor underneath.",
"36f439de-397b-8146-b48d-c8b4068c8dc2": "The Outback 5 H2O is built to make serious adventure touring accessible, carrying on a design ridden around the world since its first generation. It keeps the proven three-layer construction with detachable thermal and hydratex waterproof liners, now adding upgraded chest ventilation. Fit adjustment is thorough, from an integrated waist-belt adjuster to arm tabs and hem drawcords, and protection is strong with CE-level 2 SEEFLEX armor standard and options for level 2 back and level 1 divided chest protectors, at a Class AA rating. Storage is generous, with large waterproof front pockets and multiple inner pockets. The trade-off is the bulk and layer-juggling common to full touring systems.",
"36f439de-397b-81f2-a69e-d1a3f4cfcfbb": "The Highcrest H2O gives city riders the best of both worlds, a fully ventilated mesh jacket paired with a wet-weather hydratex waterproof layer. The over-and-under waterproofing jacket is light and compact enough to stow until rain arrives, and reflective material on both the mesh base and the rain layer aids visibility. Protection is a step up from many urban jackets: a Class AA rating reinforced with CE-level 2 SEEFLEX armor at the shoulders and elbows, plus an option for a level 2 back protector. The two-piece approach means a little more to manage, which is the cost of riding cool in the heat and dry in the rain.",
"36f439de-397b-812f-adcb-dd17e0cd6e07": "The Offtrack 3 H2O is a third-generation all-season adventure-touring jacket built around a lightweight three-layer system. A durable PWR|Shell and PWR|Ripstop outer with large, easy-action vents gives you built-in climate control, while a detachable thermal liner and an over-and-under hydratex waterproof liner adapt it to heat, cold and rain. CE-level 2 SEEFLEX armor sits at the shoulders and elbows, with options for a level 2 back protector and level 1 divided chest protectors, at a Class AA rating. Storage is generous across the shell, liners and an extra-large mesh back pocket. As with any three-layer setup, the trade is the bulk of the layers you are not wearing.",
"36f439de-397b-8139-b325-e184bfd11cb2": "The Africa is a Pol Tarres adventure off-road jacket engineered for the hottest rides, using his desert-racing experience as input. Refined ballistic mesh with laser-cut ventilation makes up to 70% of the jacket breathable, with stretchy softshell and hard-wearing ripstop placed where they are needed, so you stay cool when adventure heats up. Styling runs to bright red ripstop and dark camo mesh, with just the necessary pockets including a chest pocket with a goggle wipe. CE-level 1 SEESMART armor is thin but effective, and removable so you can wear the jacket over a protection vest. It is a Class AA jacket with no waterproofing, built for heat above all.",
"36f439de-397b-8135-a349-e27be424084e": "The Tectonic H2O is a modular adventure-travel jacket that mixes REV'IT!'s off-road and touring ideas into one climate-adaptable system. A durable 3L polyester ripstop outer shell with 3L hydratex waterproofing keeps the rain out, while an inner PWR|Shell mesh jacket flows air on hot days, and you can zip in your own base or mid layer. An important detail: the waterproof outer shell has no built-in armor and is Class B certified, meant to layer over the AA-rated mesh jacket rather than be ridden alone, so the protection lives in the mesh layer. A foldable hood and XL storage pocket add practicality.",
"36f439de-397b-815a-ba28-f9cf709ad3d8": "The Component 3 H2O is the evolution of a DIRT Series adventure favorite, refining the standout details and adding a few more. Strategically matched CORDURA ripstop and PWR|Shell stretch ripstop give it a hard-wearing look over a genuinely lightweight, purpose-built build, with 100% wind and waterproof 3L hydratex lamination and taped seams. CE-level 1 SEESMART armor is standard with a dedicated pocket for a level 2 back protector, at a Class A rating. Thoughtful tweaks include outward-facing pockets for easier glove-on access, a center-front Aquadefence ventilation zipper, and a reconfigured detachable hood that cinches around the head. It now uses a unisex fit covering men and women.",
"36f439de-397b-810a-a649-e4e0e220714e": "The Blackwater 3 H2O is an adventure off-road smock you pull on over your head, with a side-entrance zipper that makes that easy while keeping the front clean and weatherproof. A CORDURA ripstop and 3L PWR|Shell ripstop stretch outer shields against the road, and 3L hydratex waterproofing with taped seams shields against the elements, with laminated reflection at the back, hood and logo for poor visibility. CE-level 1 SEESMART armor is standard with a pocket for a level 2 back protector, at a Class A rating. The active fit is sized to slip over the Proteus protector jacket for serious adventure days, and outward-facing pockets ease glove-on access. It uses a unisex fit for men and women.",
"359439de-397b-81fd-8399-ff2ea6a3a73c": "The Convergent H2O is an adventure-touring jacket that aims squarely at value, borrowing lessons from REV'IT!'s top-end models and packaging the essentials at a friendlier price. A fixed hydratex G-liner keeps the rain out, a detachable thermal liner covers the cold, and generous direct ventilation, including a large panel behind the front zipper, keeps air moving in the heat. The rally-inspired styling and practical storage make it ready for real journeys. Protection is SEESMART CE-level 1 at the shoulders and elbows with room for a level 2 back protector. The main compromise is that the waterproof liner is fixed rather than removable, so you cannot strip it out the way you can on the pricier three-layer jackets.",
"210439de-397b-81f3-bbb5-da91f642e902": "The Eclipse 2 is a lightweight summer commuter built to keep you cool through long, hot city days. Polyester mesh panels at the front, back and inner arms send air around the whole body, and an abrasion-resistant 600-denier polyester construction adds security, with fit tabs at the waist, cuffs and bicep. SEESMART CE-level 1 armor sits at the elbows and shoulders, upgradeable to a level 2 back protector, and it uses a high share of recycled polyester. Practical touches include zipped pockets, a wind catcher behind the front zipper and a jeans loop. As a Class A summer jacket it offers no waterproofing, so it is a warm-weather, dry-conditions commuter.",
"36f439de-397b-8118-a163-c2d07f02a9e4": "The Sand 5 H2O continues an icon, a series that helped define motorcycle travel over the past 15 years, now evolved with small but meaningful refinements. It uses the proven three-layer approach with a detachable thermal liner and an over-and-under hydratex 3L waterproof liner you can wear over or under your protective layer to suit conditions. This generation leans slightly more sport-driven than the Sand 4, reflecting how adventure bikes have grown more dynamic. Protection is a Class AA rating with CE-level 2 SEEFLEX armor and options for level 2 back and level 1 divided chest protectors, and it is hydration-pack prepared. As a full touring system, expect the layer-management and bulk that come with that versatility.",
"2d1439de-397b-812d-a989-f534ecf43339": "The Eclipse 2 is a lightweight summer commuter built to keep you cool through long, hot city days. Polyester mesh panels at the front, back and inner arms send air around the whole body, and an abrasion-resistant 600-denier polyester construction adds security, with fit tabs at the waist, cuffs and bicep. SEESMART CE-level 1 armor sits at the elbows and shoulders, upgradeable to a level 2 back protector, and it uses a high share of recycled polyester. Practical touches include zipped pockets, a wind catcher behind the front zipper and a jeans loop. As a Class A summer jacket it offers no waterproofing, so it is a warm-weather, dry-conditions commuter.",
}

updated, missing = 0, []
for pid, desc in DESCRIPTIONS.items():
    try:
        n.pages.update(page_id=pid, properties={
            "Description": {"rich_text": [{"text": {"content": desc}}]},
        })
        updated += 1
        print(f"  ok  {pid}")
    except Exception as e:
        missing.append((pid, str(e)))
        print(f"  ERR {pid}: {e}")

print(f"\nDONE - {updated}/{len(DESCRIPTIONS)} descriptions written")
if missing:
    for pid, err in missing:
        print(f"  FAILED {pid}: {err}")
